addons:
  code_climate:
    repo_token: f4abd1a2e7875429c4a150f81ed9127e0507cb26b9700120d40e567d3dbcb3e4
language: node_js
node_js:
  - 8.9.0
after_success:
  - yarn add --dev codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info